image: node:latest
rules: when:manual
stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - npm install
  script:
    - echo "Building"
    - npm webpack
    - cd dependencies/nodejs && npm install
  artifacts:
    paths:
      - node_modules/
      - webpack
      - dependencies/nodejs/node_modules
test:
  stage: test

  script:
    - echo "Testing"
    - npm test
deploy:
  stage: deploy
  before_script:
    -
  script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
