image: node:latest
stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - npm install
  script:
    - echo "Building"
    - npm run webpack
    - cd dependencies/nodejs && npm install
  artifacts:
    paths:
      - node_modules/
      - webpack
      - dependencies/nodejs/node_modules

test:
  stage: test
  script:
    - echo "Testing"
    - npm test

deploy:
  image: python:latest
  rules:
    - when: manual
  stage: deploy
  script:
    - echo "Deploying"
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
    - sam deploy --template-file template.yaml --no-confirm-changeset
